---
# tasks file for php-fpm
- name: install package
  apt:
     name: php-fpm
     state: present

- name: start service
  service:
       name: php8.1-fpm
       state: started
       enabled: yes

- name: create root directory
  file:
        path: "{{ document_root }}"
        state: directory


- name: Copy website files to the server's document root
  copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

- name: Copy php-fpm config
  copy:
       src: www.conf
       dest: "/etc/php/8.1/fpm/pool.d"
       mode: preserve

- name: Restart php-fpm
  service:
        name: php8.1-fpm
        state: restarted