---
- hosts: nginx
  gather_facts: no
  become: yes
  vars:
        server_name: localhost
        document_root: /opt/nginx/ansible
        app_root: index.php
  roles:
    - users
    - php-fpm
    - nginx